FROM example-wiki:0.1.0 AS base

FROM base AS build
WORKDIR /build
RUN corepack enable \
  && corepack prepare pnpm@10.20.0 --activate \
  && pnpm config set registry https://registry.npmmirror.com

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY server/package.json server/
COPY web/package.json web/
COPY desktop/package.json desktop/
RUN pnpm install --frozen-lockfile --ignore-scripts

COPY server server
COPY web web
RUN pnpm --filter @example-wiki/web build \
  && pnpm --filter @example-wiki/server build

FROM base
COPY --from=build /build/node_modules /app/node_modules
COPY --from=build /build/server/node_modules /app/server/node_modules
COPY --from=base /app/node_modules/.pnpm/better-sqlite3@12.11.1/node_modules/better-sqlite3/build /app/node_modules/.pnpm/better-sqlite3@12.11.1/node_modules/better-sqlite3/build
COPY --from=build /build/server/dist /app/server/dist
COPY --from=build /build/web/dist /app/web/dist
